/*

 MAP3.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 12
   Tile set      : F:\Clang\03-BlockDude\resource\sprite.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map03Width 20
#define map03Height 12
#define map03Bank 0

#define map03 map03PLN0
const unsigned char map03PLN0[] =
{
  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,
  1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
  1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
  1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,1,
  1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,1,
  1,0,1,1,1,0,0,0,0,4,0,0,0,1,3,0,1,1,1,1,
  1,0,1,0,1,0,0,0,0,1,0,0,1,1,1,1,1,0,0,0,
  1,0,1,0,1,3,3,0,1,1,0,0,1,0,0,0,0,0,0,0,
  1,2,1,0,1,1,1,1,1,1,0,1,1,0,0,0,0,0,0,0,
  1,1,1,0,1,1,0,0,0,1,1,1,0,0,0,0,0,0,0,0
};

/* End of MAP3.C */
