/*

 MAP5.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 10
   Tile set      : F:\Clang\03-BlockDude\resource\sprite.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map05Width 20
#define map05Height 10
#define map05Bank 0

#define map05 map05PLN0
const unsigned char map05PLN0[] =
{
  0,1,0,1,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,1,
  1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
  1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
  1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,
  1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,
  1,0,0,0,0,0,1,3,3,3,3,0,0,0,0,0,0,0,0,1,
  2,0,0,0,0,1,1,1,1,1,1,1,4,0,0,0,0,0,0,1,
  1,0,0,1,1,1,0,0,0,0,0,1,1,0,1,0,0,0,3,1,
  1,0,1,1,0,0,0,0,0,0,0,0,1,0,1,1,0,3,3,1,
  1,1,1,1,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1
};

/* End of MAP5.C */
