/*

 MAP6.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 12
   Tile set      : F:\Clang\03-BlockDude\resource\sprite.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map06Width 20
#define map06Height 12
#define map06Bank 0

#define map06 map06PLN0
const unsigned char map06PLN0[] =
{
  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
  1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,
  1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
  2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
  1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
  1,0,0,0,0,0,0,0,0,0,0,1,0,0,3,0,0,3,3,1,
  1,3,3,0,0,0,0,0,0,0,0,1,4,3,3,0,0,1,1,1,
  1,3,3,3,0,0,0,0,0,0,0,1,1,1,1,1,0,1,1,1,
  1,1,1,1,1,0,0,0,0,1,1,1,1,1,1,1,1,1,0,0,
  1,1,1,1,1,0,0,0,3,1,1,1,1,1,1,1,1,1,1,1,
  1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,
  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
};

/* End of MAP6.C */
