/*

 SPRITE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Sprite_h_INCLUDE
#define __Sprite_h_INCLUDE

/* Bank of tiles. */
#define spriteBank 0

/* Super Gameboy palette 0 */
#define spriteSGBPal0c0 6076
#define spriteSGBPal0c1 8935
#define spriteSGBPal0c2 6596
#define spriteSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define spriteSGBPal1c0 6076
#define spriteSGBPal1c1 8935
#define spriteSGBPal1c2 6596
#define spriteSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define spriteSGBPal2c0 6076
#define spriteSGBPal2c1 8935
#define spriteSGBPal2c2 6596
#define spriteSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define spriteSGBPal3c0 6076
#define spriteSGBPal3c1 8935
#define spriteSGBPal3c2 6596
#define spriteSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define spriteCGBPal0c0 32767
#define spriteCGBPal0c1 21140
#define spriteCGBPal0c2 10570
#define spriteCGBPal0c3 0

/* Gameboy Color palette 1 */
#define spriteCGBPal1c0 32767
#define spriteCGBPal1c1 17407
#define spriteCGBPal1c2 8464
#define spriteCGBPal1c3 4234

/* Gameboy Color palette 2 */
#define spriteCGBPal2c0 32767
#define spriteCGBPal2c1 23517
#define spriteCGBPal2c2 4420
#define spriteCGBPal2c3 10591

/* Gameboy Color palette 3 */
#define spriteCGBPal3c0 32767
#define spriteCGBPal3c1 2047
#define spriteCGBPal3c2 10910
#define spriteCGBPal3c3 4234

/* Gameboy Color palette 4 */
#define spriteCGBPal4c0 6076
#define spriteCGBPal4c1 8935
#define spriteCGBPal4c2 6596
#define spriteCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define spriteCGBPal5c0 6076
#define spriteCGBPal5c1 8935
#define spriteCGBPal5c2 6596
#define spriteCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define spriteCGBPal6c0 6076
#define spriteCGBPal6c1 8935
#define spriteCGBPal6c2 6596
#define spriteCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define spriteCGBPal7c0 6076
#define spriteCGBPal7c1 8935
#define spriteCGBPal7c2 6596
#define spriteCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char spriteCGB[];
/* Start of tile array. */
extern const unsigned char sprite[];

extern const UWORD spritePalette[] = {
    spriteCGBPal0c0,    spriteCGBPal0c1,    spriteCGBPal0c2,    spriteCGBPal0c3,
    spriteCGBPal1c0,    spriteCGBPal1c1,    spriteCGBPal1c2,    spriteCGBPal1c3,
    spriteCGBPal2c0,    spriteCGBPal2c1,    spriteCGBPal2c2,    spriteCGBPal2c3,
    spriteCGBPal3c0,    spriteCGBPal3c1,    spriteCGBPal3c2,    spriteCGBPal3c3,
    spriteCGBPal4c0,    spriteCGBPal4c1,    spriteCGBPal4c2,    spriteCGBPal4c3,
};
#include "Sprite.c"
#endif

/* End of SPRITE.H */
